### ISSUE TITLE
Cannot install fabric.js in io@v1.7.1

### ISSUE THREAD

**Issue by mori-dev** [kangax/fabric.js#2115]
fabric.js version 1.5.0 cannot install in io@v1.7.1 environment.
Because canvas and jsdom in package.json is old for io@v1.7.1.
Could you update fabric to use newer canvas and jsdom?

This is install log.

```
% npm install                                                                                                                                      (git)-[maste

> canvas@1.1.6 install /Users/b05997/tmp/fabric.js/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  SOLINK_MODULE(target) Release/canvas-postbuild.node: Finished
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../node_modules/nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

...

7 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/b05997/.nodebrew/iojs/v1.7.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/b05997/.nodebrew/iojs/v1.7.1/bin/iojs" "/Users/b05997/.nodebrew/iojs/v1.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "
rebuild"
gyp ERR! cwd /Users/b05997/tmp/fabric.js/node_modules/canvas
gyp ERR! node -v v1.7.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

```

### URLs

- https://github.com/tmpvar/jsdom
- https://github.com/Automattic/node-canvas

**Comment by kangax** [comment]
I don't think node-canvas works on io. If you can find a working combination, please let us know.
