### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by newtriks** [kangax/fabric.js#2275]
I'm attempting to install *fabric* using `npm install fabric` that produces the below output, any ideas or tips?

I have a feeling it maybe related to some additional steps to configure my system: http://stackoverflow.com/a/27705973

```
$ npm install fabric
npm WARN package.json canvas@1.0.0 No description
npm WARN package.json canvas@1.0.0 No repository field.
npm WARN package.json canvas@1.0.0 No README data
npm WARN package.json fs@0.0.2 fs is also the name of a node core module.
npm WARN package.json fs@0.0.2 No description
npm WARN package.json fs@0.0.2 No repository field.
npm WARN package.json node-libs-browser@0.5.0 No repository field.
npm WARN engine fabric@1.5.0: wanted: {"node":">=0.4.0 && <1.0.0"} (current: {"node":"0.10.35","npm":"2.9.0"})
 
> canvas@1.1.6 install /Users/newtriks/src/playground/canvas/node_modules/fabric/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/newtriks/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/newtriks/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/newtriks/src/playground/canvas/node_modules/fabric/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by newtriks** [comment]
Yup, additional install of dependencies required http://fabricjs.com/fabric-intro-part-4/#node doh!
