### ISSUE TITLE
Npm installation fails canvas / node-gyp

### ISSUE THREAD

**Issue by pedro-couto** [kangax/fabric.js#3278]
Hi!

I get the following npm error while installing fabricjs, seems that canvas dependency breaks it.

**versions**
Node version: 6.3.1
Npm version: 3.10.3
Fabricjs : 1.6.4
OS version: OSX El Capitan 10.11.6

**npm error**
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/foobar/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/foobar/.nvm/versions/node/v6.3.1/bin/node" "/Users/foobar/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/foobar/foo/bar/node_modules/canvas
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:canvas@1.4.0 canvas@1.4.0 install: `node-gyp rebuild`
npm WARN install:canvas@1.4.0 Exit status 1
```

Cheers!

**Comment by asturur** [comment]
please check nodecanvas github pages
