### ISSUE TITLE
FabricJs on NodeJS for generate image from JSON

### ISSUE THREAD

**Issue by kemal-atila** [kangax/fabric.js#3412]
I want to generate image as PNG or JPEG from Nodejs.
I run
```
npm install fabric
npm install canvas
npm install jsdom
npm install xmldom
```

And than wrote a js file into project folder

```
require('fabric');
var fabric = require('fabric').fabric
var canvas = new fabric.Canvas('canvas');

```

I get  when I run node index.js 
```

 element.style = { };
                      ^

TypeError: Cannot assign to read only property 'style' of canvas
    at klass.fabric.StaticCanvas.fabric.util.createClass._createCanvasElement (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:6457:23)
    at klass.fabric.StaticCanvas.fabric.util.createClass._createLowerCanvas (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:6499:66)
    at klass.fabric.StaticCanvas.fabric.util.createClass._initStatic (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:6173:12)
    at klass.fabric.StaticCanvas._initStatic (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:26038:23)
    at klass.fabric.Canvas.fabric.util.createClass.initialize (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:8358:12)
    at new klass (/home/vagrant/Code/fabric/node_modules/fabric/dist/fabric.js:1787:23)
    at Object.<anonymous> (/home/vagrant/Code/fabric/index.js:3:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)


```

I just want to send json from php and get path of generated image from fabricjs

**Comment by asturur** [comment]
what version of node?

**Comment by kemal-atila** [comment]
the version is 5.0.0

**Comment by kemal-atila** [comment]
I changed version and tried again.

For v4.6.2
```
  throw e
        ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/vagrant/Code/fabric/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/vagrant/Code/fabric/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

for 0.10.48

```
        throw e
              ^
Error: Module version mismatch. Expected 14, got 47.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/vagrant/Code/fabric/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/vagrant/Code/fabric/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

for 0.10.

```
        throw e
              ^
Error: /home/vagrant/Code/fabric/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/vagrant/Code/fabric/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/vagrant/Code/fabric/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by asturur** [comment]
i m not a fabricjs node user, apart for testing purposes.
I think you should use `fabric.createCanvasForNode`
please check docs `fabricjs.com/docs`

**Comment by kemal-atila** [comment]
Thank you,  @asturur. Solved with fabric.createCanvasForNode
