### ISSUE TITLE
Webpack, Module parse failed: /node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by playground** [kangax/fabric.js#3640]
When build with webpack, it's throwing these errors

ERROR in ./~/canvas/build/Release/canvas.node
Module parse failed: /test1/node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/canvas/lib/bindings.js 3:17-51

**Comment by playground** [comment]
@asturur why do close this issue?  I haven't found a solution to this yet.

**Comment by asturur** [comment]
This is not a support forum. 
if you read the error there is not fabric.js or fabric.min.js giving you problems. is a node canvas module.

**Comment by thEpisode** [comment]
The problem is obvious but, you include this library in fabric.js, if you couldn't reproduce the error help to @playground to use your library without canvas-node....

**Comment by yazan-mehrez** [comment]
I'm facing this problem in Angular 9. I'm unable to implement any special loaders in my CLI, because in Angular 9 the webpack.config.js file is no longer needed.

**Comment by asturur** [comment]
what is the recommended way to not load specific binary modules? you can also try to use the fabricjs - browser version. is on non and has a '-browser' suffix after the version.

**Comment by rishabhrpg** [comment]
Is anyone able to fix this issue?
In I'm trying to use this library with Angular 9 (SSR) but seems like it can not load .node bins.
is there any workaround to make it work with angular 9?

**Comment by asturur** [comment]
if angular does not provide a guide for stubbing a dependency or is not using webpack, use the browser version.
