### ISSUE TITLE
TypeError: Cannot read property 'devicePixelRatio' of undefined on NodeJS

### ISSUE THREAD

**Issue by SeoFood** [kangax/fabric.js#3809]
## Error
```
TypeError: Cannot read property 'devicePixelRatio' of undefined
    at Object.<anonymous> (/Users/marco/PhpstormProjects/font-to-image/node_modules/fabric/dist/fabric.js:77:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/marco/PhpstormProjects/font-to-image/src/handler.js:5:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
## Version
```
fabric.js
master
```

```
npm -v
4.1.2
```

```
node -v
v7.7.4
```

## Test Case
```
node -e "require('fabric').fabric"
```
## Steps to reproduce
```bash
mkdir fabric-node-js
npm install kangax/fabric.js#master
node -e "require('fabric').fabric"
```
## Expected Behavior
It should load  FabricJS

## Actual Behavior
I guess this is something with jsdom because the Document is only:
`Document { location: [Getter/Setter] }`
in https://github.com/kangax/fabric.js/blob/b979bd5861e4193cfb122d7578d59d62cee0bfdd/HEADER.js#L24

**Comment by asturur** [comment]
could be that master branch is broken in the way it detect that node is ... node.

the master should install for you jsdom 9.12 is that the case,

**Comment by SeoFood** [comment]
Sorry I'm just stupid had to build the js file with `npm run build` first. I guess the master will nit be always built :)

**Comment by asturur** [comment]
master is built right after a release. in this case last time built was
1.7.6  while the most recent builds are in 1.x branch.

master can be in a broken state right now since we are transitioning to 2.0
. slowly.

2017-03-28 18:39 GMT+02:00 Marco Hillger <notifications@github.com>:
