### ISSUE TITLE
TypeError occurs when calling toDataURL after image filter applied

### ISSUE THREAD

**Issue by rokenchou** [kangax/fabric.js#4257]
## Version
fabricjs 2.0.0-beta.6
node-canvas 1.6.6
nodejs 6.11.0
## Steps to reproduce
run fabricjs on nodejs, 1.7.16 works fine with image filter, when update to 2.0.0, can't get it work
```
var jsonStr = '{"objects":[{"type":"circle","originX":"left","originY":"top","left":119,"top":64,"width":100,"height":100,"fill":"#6dcdd0","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.8,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"radius":50,"startAngle":0,"endAngle":6.283185307179586}]}';

 var canvas = fabric.createCanvasForNode(600, 600);

canvas.loadFromJSON(jsonStr, function() {
    canvas.renderAll();
    var dataUrl = canvas.toDataURL();

    fabric.Image.fromURL(dataUrl, function(img) {
        var filter = new fabric.Image.filters.Sepia();
        img.filters.push(filter);
        img.applyFilters();
        canvas.add(img);

        var dataUrl = canvas.toDataURL();
    });
});
```
## Expected Behavior
 canvas.toDataURL return dataurl
## Actual Behavior
```
"stack": [
    "TypeError: Image or Canvas expected",
    "    at TypeError (native)",
    "    at klass._render (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:18811:28)",
    "    at klass.drawObject (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:12675:12)",
    "    at klass.render (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:12623:14)",
    "    at klass._renderObjects (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:7082:34)",
    "    at klass.renderCanvas (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:7059:12)",
    "    at klass.renderAll (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:8994:12)",
    "    at klass.__toDataURLWithMultiplier (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:11359:12)",
    "    at klass.toDataURL (/data/web/websites/adamlv/node_workspace/monet/node_modules/fabric/dist/fabric.js:11329:19)",
    "    at Command.callback (/data/web/websites/adamlv/node_workspace/monet/api/canvas_converter.js:249:58)",
    "    at normal_reply (/data/web/websites/adamlv/node_workspace/monet/node_modules/redis/index.js:721:21)",
    "    at RedisClient.return_reply (/data/web/websites/adamlv/node_workspace/monet/node_modules/redis/index.js:819:9)",
    "    at JavascriptRedisParser.returnReply (/data/web/websites/adamlv/node_workspace/monet/node_modules/redis/index.js:192:18)",
    "    at JavascriptRedisParser.execute (/data/web/websites/adamlv/node_workspace/monet/node_modules/redis-parser/lib/parser.js:553:10)",
    "    at Socket.<anonymous> (/data/web/websites/adamlv/node_workspace/monet/node_modules/redis/index.js:274:27)",
    "    at emitOne (events.js:96:13)"
  ],
  "level": "error",
```

**Comment by asturur** [comment]
i managed to fix this:
![image](https://user-images.githubusercontent.com/1194048/29894054-6dc5ae5a-8dd4-11e7-9fba-05e67e701b8d.png)

The problem is that the filtering system create a canvas that is a jsdom canvas and not a canvas for node.
I thought it got automatic after jsdom 9 but maybe i'm wrong.

**Comment by asturur** [comment]
i ll publish a fix as soon as i undertand better what is going on.

**Comment by asturur** [comment]
Let's keep the discussion on #4231 that is the same issue, just opened before
