### ISSUE TITLE
jsdom error in nodejs

### ISSUE THREAD

**Issue by natcl** [kangax/fabric.js#4788]
## Version
2.0.2

## Test Case
I am trying to run fabricjs under node, it first complained that jsdom wasn't installed so I installed the most recent version I then get this error:

```
> var fabric = require('fabricjs').fabric
TypeError: require(...).jsdom is not a function
    at Object.<anonymous> (/Users/Nat/Desktop/node-red/canvas/node_modules/fabricjs/index.js:1:314)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
>
```
I tried older versions of json and had different errors.

Is this broken ?

This is with nodejs 8.9.4

**Comment by asturur** [comment]
you have to install jsdom 9.1.2 in order for fabric to work, or use npm install form fabricJS.

**Comment by natcl** [comment]
That still doesn't work, running the example in your documentation this is the result I get:
```
/Users/Nat/Desktop/canvas/node_modules/fabricjs/index.js:1
(function (exports, require, module, __filename, __dirname) { var fabric=fabric||{version:"1.7.11"};"undefined"!=typeof exports&&(exports.fabric=fabric),"undefined"!=typeof document&&"undefined"!=typeof window?(fabric.document=document,fabric.window=window,window.fabric=fabric):(fabric.document=require("jsdom").jsdom(decodeURIComponent("%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E")),fabric.document.createWindow?fabric.window=fabric.document.createWindow():fabric.window=fabric.document.parentWindow),fabric.isTouchSupported="ontouchstart"in fabric.document.documentElement,fabric.isLikelyNode="undefined"!=typeof Buffer&&"undefined"==typeof window,fabric.SHARED_ATTRIBUTES=["display","transform","fill","fill-opacity","fill-rule","opacity","stroke","stroke-dasharray","stroke-linecap","stroke-linejoin","stroke-miterlimit","stroke-opacity","stroke-width","id"],fabric.DPI=96,fabric.reNum="(?:[-+]?(?:\\d+|\\d*\\.

TypeError: Cannot read property 'devicePixelRatio' of undefined
    at Object.<anonymous> (/Users/Nat/Desktop/canvas/node_modules/fabricjs/index.js:1:1100)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Nat/Desktop/canvas/fab.js:2:15)
    at Module._compile (module.js:643:30)
marmelon:canvas Nat$
```

**Comment by asturur** [comment]
if you get a succesfull npm install from fabricjs it has to work.

fabric 1.7 uses jsdom 3 and can t work on node 7+. fabric 2 uses jsdom 9 and should work

**Comment by natcl** [comment]
I searched for createCanvasForNode in the sources and can't find the function, was there a refactor ?
Here's the code I'm trying to run:

```
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld.png');

var canvas = fabric.createCanvasForNode(200, 200);
var text = new fabric.Text('Hello world', {
  left: 100,
  top: 100,
  fill: '#f55',
  angle: 15
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});
```

**Comment by asturur** [comment]
createCanvasForNode is no more part of fabric.
Just use `new fabric.Canvas or new fabric.StaticCanvas`

**Comment by playground** [comment]
Yes, when I tried to use fabric.Canvas or fabric.StaticCanvas and using canvas.loadFromJSON(json) where json consists of text and image objects.  Then use canvas.createPNGStream() and save it to a file, however the saved png file only shows text objects and background image, but none of the image objects.  Any idea why?
