### ISSUE TITLE
Blur filter for backend (node.js) doesn't work

### ISSUE THREAD

**Issue by antucg** [kangax/fabric.js#4904]
## Version
2.2.2

## Test Case
No test case as it is a backend problem. Frontend is ok.

## Expected Behavior
Image should be blurred.

## Actual Behavior
Code crashes. Here is the stacktrace:

document is not defined
at klass.simpleBlur (/node_modules/fabric/dist/fabric.js:11288:40)
at klass.applyTo2d (/node_modules/fabric/dist/fabric.js:11283:38)
at klass.applyTo (/node_modules/fabric/dist/fabric.js:11279:22)
at /node_modules/fabric/dist/fabric.js:10099:24
...

The code looks like this:
`var resources = options.filterBackend.resources, canvas1, canvas2, width = options.imageData.width, height = options.imageData.height;`
`if (!resources.blurLayer1) {`
`        resources.blurLayer1 = document.createElement("canvas");`
`        resources.blurLayer2 = document.createElement("canvas");`
`}`

**Comment by asturur** [comment]
@antucg that is the solution, or reference to fabric.document.createElement...
But using fabric.util is better in this case since one day for different backend we may need different code.

How does software blur performe on nodejs?

Your PR is welocome

**Comment by asturur** [comment]
Can i see a result? i never used this Blur on node before. Does it looks like a normal blur on the canvas version?

**Comment by antucg** [comment]
PR created: https://github.com/kangax/fabric.js/pull/4905

This is the web version:
![web](https://user-images.githubusercontent.com/2089578/38725141-4abd14f8-3efe-11e8-9400-605b561441ad.png)

This is the node.js generated version:
![node](https://user-images.githubusercontent.com/2089578/38725161-5a8a6da4-3efe-11e8-8802-41b88a177ed0.png)

**Comment by asturur** [comment]
Cool!
This particular cpu based blur has been written by me, i m happy is fast. I think is also faster than StackBlur, at least it is for large images and large blur values.

Is not gaussian and it does not try to be, and it works by mixing the pixels using painting operations and opacity with drawImage.

I think is cool :D
